<style>
    #nette-debug .nette-facebookApiPanel { min-width: 700px; }
    #nette-debug .nette-facebookApiPanel h2 { font-size: 22px; }
    #nette-debug .nette-facebookApiPanel h2 small { font-size: 13px; }
    #nette-debug .nette-facebookApiPanel table { width: 100%; }
    #nette-debug .nette-facebookApiPanel table th { width: 80px; }
</style>

<h1>Queries: <?php echo $esc(count($this->calls)); ?>, time: <?php echo $esc($totalTime); ?> </h1>
<div class="nette-inner nette-facebookApiPanel">
	<?php foreach($this->calls as $call): ?>
		<h2>
			<b><?php echo $esc(strtoupper((string) $call->info['method'])); ?> <?php echo $esc((string) $call->url); ?></b>
			<small>in <?php echo $esc(number_format($call->time * 1000, 2, '.', ' ')) ?>&nbsp;ms</small>
		</h2>
		<table>
			<tr><th>Response</th><td><?php echo $click($call->result ?: $call->exception, TRUE); ?></td></tr>
			<tr><th>Params</th><td><?php echo $click($call->params, TRUE); ?></td></tr>
			<tr><th>Info</th><td><?php echo $click($call->info, TRUE); ?></td></tr>
		</table>
	<?php endforeach; ?>
</div>
